import { execFileSync } from "node:child_process";
import {
  copyFileSync,
  mkdirSync,
  readFileSync,
  statSync,
  writeFileSync,
} from "node:fs";
import { fileURLToPath } from "node:url";
import { gzipSync } from "node:zlib";

const directory = fileURLToPath(new URL(".", import.meta.url));
execFileSync("cargo", [
  "build",
  "--release",
  "--target",
  "wasm32-unknown-unknown",
  "--offline",
], {
  cwd: directory,
  stdio: "inherit",
});
mkdirSync(new URL("dist/", import.meta.url), { recursive: true });
const output = new URL("dist/blo.wasm", import.meta.url);
copyFileSync(
  new URL("target/wasm32-unknown-unknown/release/blo_wasm.wasm", import.meta.url),
  output,
);
console.log(
  `blo.wasm: ${statSync(output).size} bytes (${
    gzipSync(readFileSync(output)).length
  } bytes gzip)`,
);

// Embed the binary only in the opt-in Wasm entry; package consumers need no
// Rust toolchain, separate asset, or asynchronous fetch.
const generated = new URL("../../src/wasm/bytes.ts", import.meta.url);
mkdirSync(new URL(".", generated), { recursive: true });
writeFileSync(
  generated,
  `// Generated by build:wasm. Do not edit.\nexport const base64 = ${
    JSON.stringify(readFileSync(output).toString("base64"))
  };\n`,
);

// Compile the CURRENT TypeScript sources for parity checks and benchmarking,
// rather than accidentally measuring an old release in dist/ or node_modules/.
const reference = new URL("dist/reference/", import.meta.url);
execFileSync(process.execPath, [
  fileURLToPath(new URL("../../node_modules/typescript/bin/tsc", import.meta.url)),
  "--project",
  fileURLToPath(new URL("../../tsconfig.json", import.meta.url)),
  "--module",
  "ES2022",
  "--moduleResolution",
  "Bundler",
  "--outDir",
  fileURLToPath(reference),
], { cwd: directory, stdio: "inherit" });
writeFileSync(new URL("package.json", reference), "{\"type\":\"module\"}\n");
